### PR TITLE
First draft of SwiftLint DangerSwift plugin.

### PR DESCRIPTION
**Pull request by ashfurrow**
Based on this work: https://github.com/ashfurrow/danger-swiftlint

### CODE REVIEW

**Comment by SD10** [comment]
I can’t leave this two hearts so I’m leaving a comment!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ashfurrow** [comment]
Thanks @SD10 ! We're waiting on this PR from Marathon to get reviewed: https://github.com/JohnSundell/Marathon/pull/153 and Then we'll need the change described in it to be PR'd to Danger-Swift. _Then_ we'll be able to move forward with this. So, not done yet, but a lot of progress!

**Comment by ashfurrow** [comment]
Okay! So as of https://circleci.com/gh/Moya/Harvey/67 this is "working" in the sense that code form the plugin is successfully being executed. A huge step forward! Now I just need to port an MVP of the Ruby danger-swiftlint plugin to Swift.

**Comment by AndrewSB** [comment]
This is awesome Ash! Add me as a reviewer once this is ready 😄

**Comment by ashfurrow** [comment]
Looks like there's something wrong with how the plugin is invoking SwiftLint. I'll look into it.

**Comment by ashfurrow** [comment]
Progress! Looks like serialization errors. Hmm.

**Comment by ashfurrow** [comment]
Alrighty, this is ready for review. I also fixed the remaining SwiftLint violations. 

[The plugin](https://github.com/ashfurrow/danger-swiftlint) is ready, so I tagged and pushed a 0.1.0 release (indicating the possibility of sweeping changes before a stable 1.0). Please let me know if I can clarify anything!

**Comment by ashfurrow** [comment]
No comments, gonna assume this is good to merge.

**Comment by sunshinejr** [comment]
Oh, sorry for missing that one @ashfurrow. This is really exciting that we can write our own Danger setup in Swift and already with SwiftLint plugin in it. Great work, as always 🎉

**Comment by ashfurrow** [comment]
No worries!

**Pull request merged**
