### PR TITLE
Update the CircleCI config file to version 2.0

### PR DESCRIPTION
**Pull request by Vkt0r**
Hi guys,

This PR is just one small change to use CircleCI v2.0 as they are sunsetting v1.0 in August 😄. @sunshinejr I think this should address #22. 

Happy review! 😅

### CODE REVIEW

**Comment by Vkt0r** [comment]
@pedrovereza You're welcome! 👍

**Comment by pedrovereza** [comment]
@Vkt0r I'll just leave it open for a while so other members can have the chance to review as well 😉

**Comment by Vkt0r** [comment]
@pedrovereza Sure!

**Comment by SD10** [comment]
Don't think I have Aeryn setup for Harvey at the moment, just FYI. If this is merged maybe a maintainer can send an invite

**Comment by sunshinejr** [comment]
I invited you to the org as well @Vkt0r ;-)

**Comment by Vkt0r** [comment]
@sunshinejr Thanks for the invitation! 👍

**Pull request merged**
